name: docker

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
        -
            name: Checkout
            uses: actions/checkout@v5

        -
            name: Set Up QEMU
            uses: docker/setup-qemu-action@v3

        -
            name: Set Up Docker Buildx
            uses: docker/setup-buildx-action@v3
            with:
                driver-opts: |
                    image=moby/buildkit:buildx-stable-1

        -
            name: Login DockerHub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

        -
            name: Clean build cache
            run: |
                docker buildx prune -f -a
                docker system prune -f -a

        -
            name: Build and Push Multi-arch Image
            run: |
                # 创建构建器实例
                docker buildx create --use --name multiarch-builder
                
                # 构建并推送多架构镜像，强制不使用缓存
                docker buildx build \
                    --platform linux/amd64,linux/arm64/v8,linux/arm/v7 \
                    --tag ${{ secrets.DOCKER_USERNAME }}/xiaoya-emd-go:latest \
                    --file Dockerfile \
                    --push \
                    --no-cache \
                    --progress=plain \
                    --build-arg BUILD_DATE=$(date +%s) \
                    .

        - 
            name: Docker Hub Description
            uses: peter-evans/dockerhub-description@v5
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: ${{ secrets.DOCKER_USERNAME }}/xiaoya-emd-go
                short-description: 小雅元数据爬虫Golang版
                readme-filepath: README.md
